# Generated by Django 5.1.3 on 2024-11-24 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='code',
        ),
        migrations.AddField(
            model_name='hotel',
            name='id',
            field=models.BigAutoField(auto_created=True, default=-1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hotel',
            name='local_code',
            field=models.CharField(default=8, max_length=2),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='hotel',
            constraint=models.UniqueConstraint(fields=('city', 'local_code'), name='unique_city_local_code'),
        ),
    ]
